"""
UI Mockup showing the packet filtering interface.
This creates a visual representation of the filtering UI.
"""

print("=" * 80)
print("SKANER3 - AI Network Sniffer - Packet Viewer with Debounced Filtering")
print("=" * 80)
print()
print("Filter Controls:")
print("┌─────────────────────────────────────────────────────────────────────────────┐")
print("│ Search: [192.168.1.1_____________] [Protocol: TCP ▼] [Clear]              │")
print("│         ↑ Debounced 200ms delay    ↑ Filter dropdown                       │")
print("└─────────────────────────────────────────────────────────────────────────────┘")
print()
print("Packet Table:")
print("┌─────────┬──────────────┬──────────────┬─────────┬─────────┬─────────┬──────────┐")
print("│ Time    │ Src IP       │ Dst IP       │ Src Port│ Dst Port│ Proto   │ Length   │")
print("├─────────┼──────────────┼──────────────┼─────────┼─────────┼─────────┼──────────┤")
print("│ 10:00:01│ 192.168.1.1  │ 8.8.8.8      │ 54321   │ 53      │ UDP     │ 64       │")
print("│ 10:00:02│ 192.168.1.1  │ 93.184.216.34│ 54322   │ 80      │ TCP     │ 1460     │")
print("│ 10:00:03│ 192.168.1.1  │ 93.184.216.34│ 54322   │ 80      │ TCP     │ 512      │")
print("│ 10:00:08│ 192.168.1.1  │ 142.250.185.2│ 54327   │ 443     │ TCP     │ 1024     │")
print("│ 10:00:10│ 192.168.1.1  │ 127.0.0.1    │ 54329   │ 3306    │ TCP     │ 256      │")
print("└─────────┴──────────────┴──────────────┴─────────┴─────────┴─────────┴──────────┘")
print("         ↑ Only rows matching filter '192.168.1.1' are shown")
print("         ↑ Other rows are hidden but remain in memory")
print()
print("Features Implemented:")
print("✓ Debounced filtering with 200ms delay")
print("✓ Performance optimization - only checks IP, port, protocol, length fields")
print("✓ Bulk adding mode prevents filtering during packet bursts")
print("✓ GUI-only filtering - doesn't affect AI, alerts, or export")
print("✓ Backward compatible with existing functionality")
print("✓ Non-invasive changes - existing code preserved")
print()
print("Context Menu (right-click on row):")
print("┌──────────────────────────┐")
print("│ Copy row                 │")
print("│ ──────────────────────── │")
print("│ Filter: SRC=192.168.1.1  │")
print("│ Filter: DST=8.8.8.8      │")
print("│ Filter: PROTO=UDP        │")
print("└──────────────────────────┘")
print()
print("=" * 80)